name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Doxygen
      run:   |
             if [ "$RUNNER_OS" == "Linux" ]; then
                sudo apt-get update && sudo apt-get install -y --no-install-recommends doxygen graphviz
             elif [ "$RUNNER_OS" == "Windows" ]; then
                 choco install doxygen
                 choco install graphviz
             elif [ "$RUNNER_OS" == "MacOS" ]; then
                 brew install doxygen
                 brew install graphviz
             else
                 echo "Unsupported OS type."
                 exit 1
             fi
      shell: bash    
             
    - name: Conan installation
      id: conan
      uses: turtlebrowser/get-conan@v1.0

    - name: Conan version
      run: echo "${{ steps.conan.outputs.version }}"

    - name: Create default Conan profile
      run: conan profile new default --detect

    - name: Conan configure remotes
      run:  |
            conan config set general.revisions_enabled=1

    - name: Conan install dependencies
      run:  |
            conan install . \
            -s build_type=${{env.BUILD_TYPE}} \
            --install-folder=${{github.workspace}}/build \
            -pr:b=default \
            -pr:h=default \
            -b=missing

    - name: CMake configuration
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run:  |
            cmake -B ${{github.workspace}}/build \
            -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake \
            -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      shell: bash

    - name: Cmake build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Cmake test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}


 
